### PR TITLE
captionText with innerHTML (fixes #88)

### LINKED ISSUE #88: Change captionText to use innerHTML instead of textContent
Hi

It would be great if the output of the captionText function could contain HTML code like line breaks or links.

I suggest the following change:
original:
`this.userSettings.captionText?r.textContent=this.userSettings.captionText(e)`

new:
`this.userSettings.captionText?r.innerHTML=this.userSettings.captionText(e)`

Thank you!

### PR DESCRIPTION
**Pull request by mbabini**
Change captionText to use innerHTML instead of textContent.

Please check... (it's my first pull request ;-))

### CODE REVIEW

**Comment by midzer** [comment]
Thanks for your PR @mbabini :+1: 

Changes look good to me at first. But I hope there are no security issues with using `innerHTML`, because you could inject inline code via `<script>`.

Ofc the developer has to abuse it. Or can even users inject it somehow? What do you think @viliusle ?

**Comment by viliusle** [comment]
If developer will generate image gallery with captions from untrusted source, then yes, somebody will be able to inject malicious JS code.

we can add additional config variable, that is false, but developer can set it to true during init and allow HTML inside captions.

**Comment by viliusle** [comment]
Another idea is leave `captionText` as it was, but add `captionHTML` as new option

**Comment by midzer** [comment]
So `captionHTML` would have a higher priority than `captionText`if set.

@mbabini wanna help out and update this PR with the new option?

**Comment by midzer** [comment]
*bump*

I'm gonna start working on this one over the holidays for next minor revision.

**Comment by midzer** [comment]
Should be solved by https://github.com/midzer/tobii/commit/b43119e8471c8424ad32757f85a472b9d29259a4

**Pull request closed without merging**
