### PR TITLE
Try: Update rollup config to also provide a node/browser ESM version

### PR DESCRIPTION
**Pull request by ocean90**
This is WIP to try a rollup config which also exports an ESM version. With the ESM version I was able to reduce the file size of a custom build via npm/webpack by ~44%.

At the moment I'm not sure if a cjs version is needed. Going to review the config of some related projects.

### CODE REVIEW

**Comment by midzer** [comment]
@ocean90 Thanks for your draft.
Are you willing to continue working on this? Otherwise I might have a look when I have time...

**Comment by ocean90** [comment]
I am! I'm just not so familiar with rollup and what builds are really necessary.

**Comment by ocean90** [comment]
Related: https://twitter.com/_developit/status/1347296236282523648

**Comment by ocean90** [comment]
Created #50 which replaces Rollup with Microbundle.

**Comment by midzer** [comment]
Closed in favor of https://github.com/midzer/tobii/pull/50

**Pull request closed without merging**
